inherit_from: .rubocop_todo.yml

# Do not attempt to police vendored code, and exclude special cases
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'

StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Enabled: false

# Stick to verbose until https://bugs.ruby-lang.org/issues/10177 is closed.
Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/Not:
  Enabled: false

# comply with @ytti's exacting specifications
Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/RescueModifier:
  Enabled: false

