#%RAML 1.0
---

title: oxidized-web API
baseUri: http://oxidized.example.com
version: v1
schemas:
  - nodes: !include nodes.schema
/nodes:
  get:
    description: Get a list of nodes.
    response:
      200:
        body:
          application/json:
            schema: nodes
            example: !include nodes.sample
    queryParameters:
      format:
        displayName: format
        type: string
        description: The type of data for the API to return
        example: json
        required: false
