name: "Stale Issue/PR cleanup"
on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: 'This issue is stale because it has been open 90 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 90 days with no activity.'
          operations-per-run: 500
          days-before-stale: 90
          days-before-close: -1
